spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://<host>:6543/postgres?sslmode=require
    username: <db_user>
    password: <db_password>
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

openai:
  base-url: https://api.openai.com/v1
  api-key: ${OPENAI_API_KEY}   # read from env at runtime

  org-id: …

  project-id: …